// app/layout.jsx
import ClientLayout from "../components/ClientLayout"
import "./globals.css";

export const metadata = {
  title: "Google Docs",
  description: "Generated by create next app",
};

export default function RootLayout({children}) {
  return (
    <html lang="en">
      <body>
        <ClientLayout>{children}</ClientLayout>
      </body>
    </html>
  );
}
